import 'package:test/test.dart';
import 'package:wenzagent/src/agent/entity/entity.dart';

void main() {
  group('Message ID Consistency Tests', () {
    group('MessageInput ID Handling', () {
      test('should preserve provided message ID in toMap', () {
        final input = MessageInput(
          content: 'Test message',
          id: 'custom-id-123',
        );

        final map = input.toMap();

        expect(map['id'], equals('custom-id-123'));
      });

      test('should not include id field in toMap when id is null', () {
        final input = MessageInput(
          content: 'Test message',
        );

        final map = input.toMap();

        expect(map.containsKey('id'), isFalse);
      });

      test('should preserve message ID through serialization cycle', () {
        final originalInput = MessageInput(
          content: 'Test message',
          id: 'test-uuid-456',
        );

        // Serialize
        final map = originalInput.toMap();
        
        // Deserialize
        final deserializedInput = MessageInput.fromMap(map);

        expect(deserializedInput.id, equals('test-uuid-456'));
      });

      test('should handle UUID format message ID', () {
        final uuid = '550e8400-e29b-41d4-a716-446655440000';
        final input = MessageInput(
          content: 'Test message',
          id: uuid,
        );

        final map = input.toMap();
        final deserialized = MessageInput.fromMap(map);

        expect(deserialized.id, equals(uuid));
      });
    });

    group('SendMessageRequest', () {
      test('should preserve message data including ID', () {
        final messageData = {
          'id': 'msg-123',
          'content': 'Test message',
          'type': 'text',
        };

        final request = SendMessageRequest(
          employeeId: 'emp-456',
          messageData: messageData,
        );

        final map = request.toMap();
        final deserialized = SendMessageRequest.fromMap(map);

        expect(deserialized.messageData['id'], equals('msg-123'));
        expect(deserialized.messageData['content'], equals('Test message'));
      });

      test('should handle message data without ID', () {
        final messageData = {
          'content': 'Test message',
          'type': 'text',
        };

        final request = SendMessageRequest(
          employeeId: 'emp-456',
          messageData: messageData,
        );

        final map = request.toMap();
        final deserialized = SendMessageRequest.fromMap(map);

        expect(deserialized.messageData.containsKey('id'), isFalse);
        expect(deserialized.messageData['content'], equals('Test message'));
      });
    });

    group('Message ID Generation', () {
      test('should generate valid UUID format', () {
        final input1 = MessageInput(content: 'Message 1');
        final input2 = MessageInput(content: 'Message 2');

        // IDs should be generated by the caller (AgentProxy)
        // This test just verifies UUID format
        final uuidRegExp = RegExp(
          r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
          caseSensitive: false,
        );

        // Simulate UUID generation (same as in AgentProxy)
        final uuid1 = input1.id; // null initially
        final uuid2 = input2.id; // null initially

        expect(uuid1, isNull);
        expect(uuid2, isNull);

        // AgentProxy would generate UUIDs like this:
        // final uuid = const Uuid().v4();
        // This would create valid UUIDs
      });

      test('should accept custom ID format', () {
        final customId = 'custom-msg-20260407-123456';
        final input = MessageInput(
          content: 'Test',
          id: customId,
        );

        expect(input.id, equals(customId));
        
        final map = input.toMap();
        expect(map['id'], equals(customId));
      });
    });
  });
}
